version: '3'
services: 
   chatter-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: 'chatter-db'
    environment:
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "qAwSerF1!"
     MSSQL_PID: Express
    ports:
     - "1433:1433"
   chatter-security:
    build: 'Chatter.Security/Chatter.Security.DataAccess'
    container_name: 'chatter-security'
    ports:
     - "5320:80"
   chatter-rabbitmq:
    image: rabbitmq:3-management
    container_name: 'chatter-rabbitmq'
    environment:
      hostname: 'chatter-rabbitmq'
    ports:
     - "8080:15672"
     - "8081:5672"

   chatter-domain:
    build: 'Chatter.Domain'
    container_name: 'chatter-domain'
    ports:
     - "8082:80"
   chatter-email:
    build: 'Chatter.Email'
    container_name: 'chatter-email'
    tty: true
    stdin_open: true
    restart: on-failure
    depends_on:
      - chatter-rabbitmq

  
